In [2]:
import numpy as np 
np.array([[1,2],[3, 4]]) @ np.array([[1],[1]]) # 矩阵 x 列

array([[3],
       [7]])

In [2]:
np.array([[1,2],[3, 4]]) @ np.array([1,1]) # 矩阵 x 行 ?

array([3, 7])

In [3]:
np.array([1,1]) @ np.array([[1],[1]])  # 行 x 列

array([2])

In [4]:
np.array([[1],[1]]) @ np.array([[2]]) # 列 X 数 

array([[2],
       [2]])

In [5]:
np.array([[1],[1]]) @ np.array([2]) # 列 x 数 ?

array([2, 2])

In [6]:
?np.array([1,1]) @ np.array([2]) # 行 x 数 ?

Object `np.array([1,1]) @ np.array([2]) # 行 x 数 ` not found.


In [7]:
# np.array([1,1]) @ np.array([[2]]) # 行 x 数 ?

In [8]:
# np.array([2]) @ np.array([2]) # 数 × 数 ?

In [9]:
# np.array([1]) @ np.array([2]) @ np.array([2]) # 数 × 数 x 数 ?

In [10]:
np.array([[0.1], [0.1]]) - np.array([[1], [1]]).dot(np.array([1]))

array([[-0.9, -0.9],
       [-0.9, -0.9]])

In [11]:
np.array([[1], [1]]).dot(np.array([1]))

array([1, 1])

In [12]:
np.array([[1, 1]]).T

array([[1],
       [1]])

In [13]:
np.linalg.inv(np.array([[1]]))

array([[1.]])

In [14]:
np.array([[0.00487013 ,0.00487013]]).shape

(1, 2)

In [15]:
np.array([1, 1]).reshape(2,1)

array([[1],
       [1]])

In [16]:
np.array([[0.00487013, 0.00487013]]).dot(np.array([[1, 1]]).reshape(2, 1)).reshape(1)

array([0.00974026])

In [17]:
0.1 + np.random.rand(1)

array([0.93305816])

In [18]:
np.array([0.3]).dot(np.array(1))

array([0.3])

In [3]:
np.mat([1])

matrix([[1]])